# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snaptime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snaptime
  pod 'SnapKit','~> 5.6.0'
  pod 'Alamofire', '~>5.6.4'
  pod 'Kingfisher', '~> 7.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
